Repository macnev2013/gh-actions-test, pull requests merged in 2022-03, with the labels that each got.

#1 Update main.yml
  .github/workflows/main.yml
Labels: minor

#14 label test
  README.md
Labels: bug, minor

#16 Update README.md
  README.md
Labels: testing

#18 testing release
  .github/workflows/pr-bump.yml
Labels: release:major

#19 Update README.md
  README.md
Labels: release:minor

#20 Update README.md
  README.md
Labels: release:patch, release:minor, release:major

#21 Update README.md
  README.md
Labels: documentation, release:major

#22 Update README.md
  README.md
Labels: documentation

#24 Update README.md
  README.md
Labels: bug, duplicate, release:minor, release:test

#25 Update README.md
  README.md
Labels: release:major

#28 Update pr-bump.yml
  .github/workflows/pr-bump.yml
Labels: bug, release:major

#29 Update pr-bump.yml
  .github/workflows/pr-bump.yml
Labels: good first issue, release:patch

#30 Update pr-bump.yml
  .github/workflows/pr-bump.yml
Labels: bug, release:major

#31 Update pr-bump.yml
  .github/workflows/pr-bump.yml
Labels: bug

#32 Update pr-bump.yml
  .github/workflows/pr-bump.yml
Labels: release:major

#33 Update pr-bump.yml
  .github/workflows/pr-bump.yml
Labels: bug

#34 Update README.md
  README.md
Labels: release:major

#37 Update README.md
  README.md
Labels: bug, release:minor

#38 Update pr-bump.yml
  .github/workflows/pr-bump.yml
Labels: bug, release:major

#40 Update pr-bump.yml
  .github/workflows/pr-bump.yml
Labels: bug, release:major

#42 Update pr-bump.yml
  .github/workflows/pr-bump.yml
Labels: bug, release:minor

#43 Update pr-bump.yml
  .github/workflows/pr-bump.yml
Labels: release:major

#44 Update pr-bump.yml
  .github/workflows/pr-bump.yml
Labels: release:major

#45 Update pr-bump.yml
  .github/workflows/pr-bump.yml
Labels: release:major

#47 Update README.md
  README.md
Labels: release:minor

#48 Update tag.yml
  .github/workflows/tag.yml
Labels: release:minor

#49 Update tag.yml
  .github/workflows/tag.yml
Labels: release:minor
